---
- name: Shark - Installing Generic Nagios Plugins
  package:
    name: nagios-plugins-all.x86_64
    state: latest

- name: Shark - Installing Shark Plugins
  hosts: shark_server
  gather_facts: yes
  strategy: free
  become: true

  roles:
  - sma
  - backtest 
  - strategy
  - yahoo_finance_data
