---
- name: Shark - Installing Shark Plugins
  hosts: localhost
  connection: local 
  gather_facts: yes
  strategy: free
  become: true

  vars:
   nagios_plugins_dir: "/usr/lib64/nagios/plugins/"
   nagios_conf_d: "/usr/local/nagios/etc/conf.d/"

  roles:
  - sma
  - ema
  - backtest 
  - strategy
  - yahoo_finance_data
  - correlation
