---
# tasks file for ema

- include: dependencies.yml

- name: Installing plugin - ema.py
  copy:
   src: ema.py
   dest: /usr/lib64/nagios/plugins/
   mode: '755'
   
- name: Installing command definition - ema.cfg
  copy:
   src: ema.cfg
   dest: /usr/local/nagios/etc/conf.d/
